export const dashboardHtml = `<!doctype html>
<html lang="it">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Creative Image Bridge</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171717;background:#f4f4f2}body{max-width:1180px;margin:0 auto;padding:28px}.hero{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:24px}.pill{font-size:12px;border:1px solid #bbb;border-radius:99px;padding:6px 10px;background:white}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:18px}.card{background:#fff;border:1px solid #ddd;border-radius:16px;padding:18px;box-shadow:0 3px 18px rgba(0,0,0,.04)}h1{margin:0;font-size:34px}h2{margin:0 0 14px;font-size:18px}label{display:block;font-size:12px;font-weight:700;margin:10px 0 5px}input,textarea,select,button{box-sizing:border-box;width:100%;font:inherit;border-radius:9px;border:1px solid #c9c9c9;padding:9px 10px;background:#fff}textarea{min-height:130px;resize:vertical}button{margin-top:12px;background:#171717;color:white;border:none;font-weight:700;cursor:pointer}button.secondary{background:white;color:#171717;border:1px solid #aaa}.row{display:grid;grid-template-columns:1fr 1fr;gap:9px}.muted{color:#666;font-size:12px;line-height:1.45}.item{padding:10px 0;border-top:1px solid #eee;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.thumb{width:88px;height:66px;object-fit:cover;border-radius:8px;border:1px solid #ddd}.status{white-space:pre-wrap;background:#111;color:#eee;border-radius:10px;padding:10px;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;min-height:46px}.preview{width:100%;max-height:430px;object-fit:contain;background:#eee;border-radius:12px;margin-top:12px}code{background:#eee;padding:2px 5px;border-radius:5px}
</style>
</head><body>
<div class="hero"><div><div class="pill" style="display:inline-block">MCP + REST</div><h1>Creative Image Bridge</h1><div class="muted">Asset Vault + OpenAI GPT Image + output in formati ADV esatti.</div></div><div style="min-width:300px"><label>Bridge key</label><input id="key" type="password" placeholder="BRIDGE_API_KEY" /></div></div>
<div class="grid">
<section class="card"><h2>1. Carica reference / prodotti / loghi</h2><input id="files" type="file" accept="image/*" multiple/><label>Etichetta</label><input id="label" placeholder="es. Felpa nera prodotto originale"/><button onclick="uploadAssets()">Carica nell'Asset Vault</button><div id="uploadStatus" class="muted"></div><div id="assets"></div></section>
<section class="card"><h2>2. Genera un visual</h2><label>Prompt</label><textarea id="prompt" placeholder="Fotografia pubblicitaria..."></textarea><div class="row"><div><label>Modello</label><select id="model"><option value="gpt-image-2.5-flare">Flare — veloce</option><option value="gpt-image-2.5-sunburst">Sunburst — qualità/edit</option></select></div><div><label>Qualità</label><select id="quality"><option>low</option><option selected>medium</option><option>high</option><option>xhigh</option><option>max</option></select></div></div><div class="row"><div><label>Larghezza finale</label><input id="width" type="number" value="1080"/></div><div><label>Altezza finale</label><input id="height" type="number" value="1350"/></div></div><div class="row"><div><label>Sfondo</label><select id="background"><option>auto</option><option>opaque</option><option>transparent</option></select></div><div><label>Adattamento</label><select id="post"><option value="cover">cover</option><option value="contain">contain</option><option value="blur-extend">blur-extend</option></select></div></div><button onclick="generate()">Genera</button><div id="genStatus" class="status">Pronto.</div><img id="preview" class="preview" style="display:none"/></section>
<section class="card"><h2>3. Output</h2><div class="muted">Gli stessi <code>output_id</code> sono disponibili a Claude via MCP.</div><button class="secondary" onclick="loadOutputs()">Aggiorna output</button><div id="outputs"></div></section>
<section class="card"><h2>Collegamento Claude</h2><div class="muted">Dopo il deploy pubblico, usa come URL del Custom Connector:<br/><br/><code>https://TUO-DOMINIO/mcp</code><br/><br/>Authentication: <b>No sign in</b><br/>Request header:<br/><code>x-bridge-key: &lt;BRIDGE_API_KEY&gt;</code><br/><br/>L'OpenAI API key resta esclusivamente sul server.</div></section>
</div>
<script>
const key=()=>document.getElementById('key').value;
const headers=()=>({'Content-Type':'application/json','x-bridge-key':key()});
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...headers(),...(opts.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function toB64(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result).split(',')[1]);fr.onerror=rej;fr.readAsDataURL(file)})}
async function uploadAssets(){try{const list=[...document.getElementById('files').files];if(!list.length)return;for(const f of list){document.getElementById('uploadStatus').textContent='Carico '+f.name+'...';await api('/api/assets',{method:'POST',body:JSON.stringify({filename:f.name,mime_type:f.type||'image/png',data_base64:await toB64(f),label:document.getElementById('label').value})})}document.getElementById('uploadStatus').textContent='Caricamento completato.';await loadAssets()}catch(e){document.getElementById('uploadStatus').textContent=e.message}}
async function loadAssets(){try{const j=await api('/api/assets');document.getElementById('assets').innerHTML=j.assets.map(a=>'<div class="item"><div><b>'+a.label+'</b><div class="muted">'+a.id+' · '+a.filename+'</div></div><button class="secondary" style="width:auto;margin:0" onclick="copyText(\''+a.id+'\')">Copia ID</button></div>').join('')}catch(e){document.getElementById('assets').innerHTML='<div class="muted">'+e.message+'</div>'}}
async function generate(){const s=document.getElementById('genStatus');try{s.textContent='Generazione in corso...';const j=await api('/api/generate',{method:'POST',body:JSON.stringify({prompt:document.getElementById('prompt').value,model:document.getElementById('model').value,quality:document.getElementById('quality').value,background:document.getElementById('background').value,final_width:Number(document.getElementById('width').value),final_height:Number(document.getElementById('height').value),post_process_mode:document.getElementById('post').value,output_format:'png'})});s.textContent=JSON.stringify(j,null,2);if(j.outputs?.[0]?.id){const r=await fetch('/api/outputs/'+j.outputs[0].id+'/content',{headers:{'x-bridge-key':key()}});const blob=await r.blob();const p=document.getElementById('preview');p.src=URL.createObjectURL(blob);p.style.display='block'}await loadOutputs()}catch(e){s.textContent='Errore: '+e.message}}
async function loadOutputs(){try{const j=await api('/api/outputs');document.getElementById('outputs').innerHTML=j.outputs.map(o=>'<div class="item"><div><b>'+o.label+'</b><div class="muted">'+o.id+' · '+(o.metadata?.model||o.metadata?.operation||'')+'</div></div><button class="secondary" style="width:auto;margin:0" onclick="previewOutput(\''+o.id+'\')">Apri</button></div>').join('')}catch(e){document.getElementById('outputs').innerHTML='<div class="muted">'+e.message+'</div>'}}
async function previewOutput(id){const r=await fetch('/api/outputs/'+id+'/content',{headers:{'x-bridge-key':key()}});const blob=await r.blob();const u=URL.createObjectURL(blob);window.open(u,'_blank')}
function copyText(t){navigator.clipboard.writeText(t)}
</script></body></html>`;
